export const environment = {
    production: false,
    BASE_URL:'http://localhost:3000',
    USER_BASE_URL:'http://localhost:3000/users',
    EVENT_BASE_URL:'http://localhost:3000/events',
    TICKET_BASE_URL:'http://localhost:3000/ticket',
    AUDIENCE_BASE_URL:'http://localhost:3000/audience',
    ORGANISATION_BASE_URL:'http://localhost:3000/organisation',
    USER:
    {
        GET_USER_LOGIN:'login',
        GET_ALL_USER:'list',
        GET_USER:'search',
        CREATE_USER:'signup',
        UPDATE_USER:'update',
        DELETE_USER:'delete',
        LOGGED_OUT:'logout',
        LOGIN:'isLogin',
        FORGOT:'forgotPassword'
    },
    EVENT:
    {
        GET_ALL_EVENT:'listEvent',
        GET_EVENT:'myEvent',
        CREATE_EVENT:'addEvent',
        UPDATE_EVENT:'updateEvent',
        DELETE_EVENT:'deleteEvent',
        EVENT_BY_TYPE:'searchType',
        GET_EVENT_DETAIL:'eventDetail'
        // PG_BY_RENT:'searchRent',
    },
    PHONE:
    {
        SEND_CODE:'verify',
        CHECK_CODE:'verifycode'
    },
    TICKET:{
        CREATE_TICKET:'createTicket',
        GET_TICKET:'getTicket',
        MY_TICKET:'myTicket',
        UPDATE_TICKET:'updateTicket'
    },
    AUDIENCE:{
        LIST_AUDIENCE:'listAudience',
        BOOK_EVENT:'bookEvent',
        MY_EVENTS:'myEvents'
    },
    ORGANISATION:{
        LIST_ORGANISATION:'listOrganisation',
        ADD_ORGANISATION:'addOrganisation',
        ADD_LOGO:'addLogo',
        UPDATE_ORGANISATION:'updateOrganisation',
        MY_ORGANISATION:'myOrganisation',
        APPLY:'apply',
        SEARCH:'search',
        ORGANISATION_DETAIL:'organisation-detail',
        MY_APPLICATION:'my-application'
    }

  };
